# 描述 Compose 文件的版本信息
version: "3"

# 定义服务，可以多个
services:
  redis-6379: # 服务名称
    image: redis # 创建容器时所需的镜像
    container_name: redis-6379 # 容器名称
    network_mode: "host" # host 网络模式
    volumes: # 数据卷，目录挂载
      - /data/code/redis_experiment/docker/cluster_conf/redis_6379.conf:/usr/local/etc/redis/redis.conf
      - /data:/data
    command: redis-server /usr/local/etc/redis/redis.conf 

  redis-6380: # 服务名称
    image: redis # 创建容器时所需的镜像
    container_name: redis-6380 # 容器名称
    network_mode: "host" # host 网络模式
    volumes: # 数据卷，目录挂载
      - /data/code/redis_experiment/docker/cluster_conf/redis_6380.conf:/usr/local/etc/redis/redis.conf
      - /data:/data
    command: redis-server /usr/local/etc/redis/redis.conf 

  redis-6381: # 服务名称
    image: redis # 创建容器时所需的镜像
    container_name: redis-6381 # 容器名称
    network_mode: "host" # host 网络模式
    volumes: # 数据卷，目录挂载
      - /data/code/redis_experiment/docker/cluster_conf/redis_6381.conf:/usr/local/etc/redis/redis.conf
      - /data:/data
    command: redis-server /usr/local/etc/redis/redis.conf 

 
  redis-6382: # 服务名称
    image: redis # 创建容器时所需的镜像
    container_name: redis-6382 # 容器名称
    network_mode: "host" # host 网络模式
    volumes: # 数据卷，目录挂载
      - /data/code/redis_experiment/docker/cluster_conf/redis_6382.conf:/usr/local/etc/redis/redis.conf
      - /data:/data
    command: redis-server /usr/local/etc/redis/redis.conf 

  

  
