version: "3"

services:
  redis-6379:
    image: redis
    container_name: redis-6379
    network_mode: "host"
    volumes:
      - /data/code/redis_experiment/docker/cluster_conf/redis_6379.conf:/usr/local/etc/redis/redis.conf
      - /data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6380:
    image: redis
    container_name: redis-6380
    network_mode: "host"
    volumes:
      - /data/code/redis_experiment/docker/cluster_conf/redis_6380.conf:/usr/local/etc/redis/redis.conf
      - /data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6381:
    image: redis
    container_name: redis-6381
    network_mode: "host"
    volumes:
      - /data/code/redis_experiment/docker/cluster_conf/redis_6381.conf:/usr/local/etc/redis/redis.conf
      - /data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-6382:
    image: redis
    container_name: redis-6382
    network_mode: "host"
    volumes:
      - /data/code/redis_experiment/docker/cluster_conf/redis_6382.conf:/usr/local/etc/redis/redis.conf
      - /data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

